# Site settings
title: Volt Docs
email: 
description: "Documentation and tutorials for Volt."
baseurl: ""
url: ""
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty

# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'notes.md', 'README.md', 'volt-colors']
