# Site settings
title: Volt Docs
email: 
description: "Documentation and tutorials for Volt."
baseurl: ""
url: ""
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: none

# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'notes.md', 'README.md', 'volt-colors']

# Gems
gems:
  - jekyll-archives
  - jekyll-sitemap

# Jekyll Archives
jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
