# Site settings
title: Volt Docs
description: >
  Documentation and tutorials for Volt. The categories below are a great place to get started, or you can browse <a href="/article-index/">all the articles</a>.</p><p>Have a question or just want to say hi? Email us at <a href="mailto:hello@voltcloud.io">hello@voltcloud.io</a>.
url: "https://docs.voltcloud.io"
copyright: Ars Mentis LLC
tracking_id: 'UA-81364729-3'

# Build settings
kramdown:
  input: GFM

permalink: /:categories/:title/

index_categories:
  - Getting Started

# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'volt-colors', 'circle.yml', 'vendor', 'deploy.sh']

# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'

# Footer content
footer: >
  Questions? Comments? You can reach us at <a href="mailto:hello@voltcloud.io">hello@voltcloud.io</a>.
