# Site settings
title: Volt Docs
description: "Documentation and tutorials for Volt."
url: "https://docs.voltcloud.io"

# Build settings
kramdown:
  input: GFM

permalink: /:categories/:title/

# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'volt-colors']

# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'
